version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: postcodes_app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/local
    volumes:
      - .:/app

volumes:
  mongo_data:
